//
//  ApiJsonModel+Extra.swift
//
//
//  Created by Miguel de Icaza on 3/24/23.
//

// This file contains manually written extensions for autogenerated model sources.

public protocol JGodotEnum {
    var name: String { get }
    var values: [JGodotValueElement] { get }
    var isBitfield: Bool? { get }
}

extension JGodotEnum {
    public var isBitfield: Bool? { return nil }
}

extension JGodotBuiltinClassEnum: JGodotEnum {}
extension JGodotGlobalEnumElement: JGodotEnum {}

// Protocol to share features between JGodotExtensionClass and JGodotBuiltinClass
public protocol JClassInfo {
    var name: String { get }
    associatedtype EnumType: JGodotEnum
    var enums: [EnumType]? { get }
}

extension JGodotBuiltinClass: JClassInfo {}
extension JGodotExtensionAPIClass: JClassInfo {}

//preserving preferred naming convention for JGodotArgumentMeta
public typealias JGodotArgumentMeta = JGodotMeta

// Used to unify the class methods and the utility methods
public protocol MethodDefinition {
    var name: String { get }
    var isConst: Bool { get }
    var isVararg: Bool { get }
    var isStatic: Bool { get }
    var isVirtual: Bool { get }
    var optionalHash: Int? { get }
    var returnValue: JGodotReturnValue? { get }
    var description: String? { get }
    var arguments: [JGodotArgument]? { get }
}

extension JGodotClassMethod: MethodDefinition {
    public var optionalHash: Int? { hash }
}

extension JGodotUtilityFunction: MethodDefinition {
    public var isConst: Bool { true }
    public var isStatic: Bool { true }
    public var isVirtual: Bool { false }
    public var optionalHash: Int? { hash }
    public var returnValue: JGodotReturnValue? {
        if let returnType {
            return JGodotReturnValue (type: returnType, meta: nil)
        } else {
            return nil
        }
    }
}

public protocol TypeWithMeta {
    var type: String {get}
    var meta: JGodotArgumentMeta? { get }
}

extension JGodotArgument: TypeWithMeta {}
extension JGodotReturnValue: TypeWithMeta {}

// computed property to preserve snake case in SwiftGodot code
public protocol BriefDescriptionProvider {
    associatedtype BriefDescriptionType
    var brief_description: BriefDescriptionType { get }
    var briefDescription: BriefDescriptionType { get }
}

extension BriefDescriptionProvider where BriefDescriptionType == String {
    public var brief_description: String {
        return briefDescription
    }
}

extension BriefDescriptionProvider where BriefDescriptionType == String? {
    public var brief_description: String? {
        return briefDescription
    }
}
extension JGodotBuiltinClass: BriefDescriptionProvider {}
extension JGodotExtensionAPIClass: BriefDescriptionProvider {}

// hash function implementation to account for hashValue deprecation
extension JSONNull {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(0)
    }
}
