//
//  TestSuiteGenerator.swift
//  SwiftGodot
//
//  Scans test sources for @SwiftGodotTestSuite classes and generates the
//  `TestRunnerNode.generatedSuites` array, so suites no longer need to be
//  registered by hand.
//

import Foundation
import ArgumentParser
import SwiftSyntax
import SwiftParser

@main
struct TestSuiteGenerator: ParsableCommand {
    @Option(name: .shortAndLong, help: "Output file for the generated suites list")
    var outputFile: String

    @Argument(help: "Source files to scan for @SwiftGodotTestSuite classes.")
    var sourceFiles: [String]

    @Option(name: .shortAndLong, help: "Produce more output.")
    var verbose: Bool = false

    mutating func run() throws {
        let visitor = TestSuiteSearchingVisitor(viewMode: .all, logger: verbose ? logVerbose : nil)

        logVerbose("Scanning source files...")
        for file in sourceFiles {
            logVerbose("Scanning '\(file)'...")
            let source = try String(contentsOf: URL(fileURLWithPath: file))
            let fileSyntax = Parser.parse(source: source)

            visitor.walk(fileSyntax)
        }

        // Sort for a stable, deterministic output regardless of file ordering.
        let suites = visitor.suites.sorted()

        let entries = suites
            .map { name in "        \(name)()," }
            .joined(separator: "\n")

        let source = """
        // Generated by TestSuiteGenerator. Do not edit.
        import SwiftGodotTestMacros

        extension TestRunnerNode {
            /// All @SwiftGodotTestSuite suites discovered at build time.
            static let generatedSuites: [any SwiftGodotTestSuiteProtocol] = [
        \(entries)
            ]
        }

        """

        let count = suites.count
        logVerbose("Writing \(count) suites to '\(outputFile)'...")
        let outputURL = URL(fileURLWithPath: outputFile)
        try source.write(to: outputURL, atomically: true, encoding: .utf8)
        log("Generated TestRunnerNode.generatedSuites with \(count) suites, in \(outputURL.lastPathComponent).")
    }

    /// Log a message to the console.
    func log(_ message: String) {
        print(message)
    }

    /// Log a message to the console if verbose mode is enabled.
    func logVerbose(_ message: String) {
        if verbose {
            print(message)
        }
    }
}
