//
//  main.swift
//  SwiftGodotMacroLibrary
//
//  Macro plugin shim for SwiftGodotBinary.  The macro implementations and
//  swift-syntax are already compiled into the SwiftGodotMacroPlugin
//  XCFramework, so this target only starts them.  Its module name must stay
//  `SwiftGodotMacroLibrary`, which is the module every SwiftGodot macro
//  declaration names in `#externalMacro`.
//
//  The entry point is declared here instead of imported from a header: an
//  XCFramework that carries headers copies them into the client's shared
//  include directory, where its `module.modulemap` collides with the one from
//  GDExtension.xcframework.  A parameterless function that returns Int32 has
//  the same calling convention in C and in Swift, so this declaration matches
//  the `@_cdecl` definition in the prebuilt library.
//
//  Generated by scripts/update-binary-package; edit that template instead.
//

#if canImport(Darwin)
import Darwin
#endif

@_silgen_name("swiftgodot_macro_plugin_main")
func swiftgodot_macro_plugin_main() -> Int32

exit(swiftgodot_macro_plugin_main())
